language: node_js
node_js: '10'
sudo: required
services:
  - docker
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

branches:
  only:
    - master
    - development

cache:
  directories:
    - node_modules

before_install:
  - docker run -d -p 8080:8080 rhizomik/textannot-api
  - while ! nc -z localhost 8080; do sleep 10; done
  - docker ps -a

install:
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser

script:
  - npm run lint
#  - npm run e2e
  - npm run build

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin;
      export REPO=rhizomik/textannot;
      export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`;
      docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .;
      docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG;
      docker push $REPO;
    fi
